### ISSUE TITLE
CSS - height of the slider-handle

### ISSUE THREAD

**Issue by ConvMe** [eonpatapon/gnome-shell-extensions-mediaplayer#82]
When I try to change the height of the slider-handle in the gnome-shell.css the height of the extension handles doesn't change.

``` css
.popup-slider-menu-item {
    height: 1em;
}
```
